### ISSUE TITLE
'gzip,deflate' vs 'gzip, deflate'

### ISSUE THREAD

**Issue by Xood** [http2jp/hpack-test-case#24]
In haskell-http2-linear I get from for decoding story_02.json the header value "gzip,deflate".
But the json file says "gzip, deflate".
For a test case it should be 100% match, even if it might not matter in this case.

Can someone validate, it might just be my decoder being wrong (yet it does not mess up any other strings).
This might happen in other files too (like it does with the same file in haskell-http2-linear-huffman)

**Comment by kazu-yamamoto** [comment]
All test files use ""gzip, deflate", not ""gzip,deflate".
Other implementations can decode `story_02.json` correctly.

**Comment by Xood** [comment]
Thank you for the reply. 
You are correct. I checked the official version at http://httpwg.org/specs/rfc7541.html and it uses a space the sperate them both. My Static Table did not contain a space, hence it was giving me a false result.

Sorry about that and and I am happy you made/maintain this repository.
