### ISSUE TITLE
maybe add a LICENSE file

### ISSUE THREAD

**Issue by weissi** [http2jp/hpack-test-case#27]
The readme mentions that this is licensed under the terms of the MIT license but I think it would be best to add a license file containing the terms of the MIT license.

**Comment by reyk** [comment]
Is this project dead? Adding a LICENSE file would at least allow to fork or import it elsewhere. I don’t think the MIT comment without an explicit license is enough.

**Comment by pavelrappo** [comment]
Dear authors and contributors, I have the same question as @reyk. For the sake of the effort that has already been spent on this project, consider adding a LICENSE file. That will allow this project to be useful in places where it would not be possible otherwise.

**Comment by kazu-yamamoto** [comment]
Sorry for the delay. We added LICENSE. Would you check it out?

**Comment by reyk** [comment]
Thank you, Kazu-san! That’s perfect.

**Comment by weissi** [comment]
Thank you!
